2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /workspace/streamGPT/wandb/run-20250212_134943-l0pmbtn3/logs/debug.log
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /workspace/streamGPT/wandb/run-20250212_134943-l0pmbtn3/logs/debug-internal.log
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc920160d60>
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:init():756] calling init triggers
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:init():789] starting backend
2025-02-12 13:49:43,780 INFO    MainThread:93455 [wandb_init.py:init():793] sending inform_init request
2025-02-12 13:49:43,781 ERROR   MainThread:93455 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 794, in init
    service.inform_init(
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 144, in inform_init
    self._client.send(inform_init=request)
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 212, in send
    self.send_server_request(server_req)
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/workspace/streamGPT/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
